---
- name: update n1 servers
  hosts: n1

  tasks:
    - name: Create directory
      file:
        path: /home/ec2-user/new_dir
        state: directory
    - name: Create directory
      file:
        path: /home/ec2-user/new_dir1
        state: directory

- name: update n2 servers
  hosts: n2

  tasks:
    - name: Create directory
      file:
        path: /home/ec2-user/new_dir1
        state: directory
    - name: Create directory
      file:
        path: /home/ec2-user/new_dir2
        state: directory

- name: update group servers
  hosts: g1

  tasks:
    - name: Create directory
      file:
        path: /home/ec2-user/new_dir_group1
        state: directory        
...
