---
- name: Install HTTP server
  hosts: n2
  become: yes

  tasks:
    - name: Install HTTP
      yum:
        name: httpd
        state: present   

    - name: start httpd
      service:
        name: httpd
        state: started     
    - name: Enable httpd
      service:
        name: httpd
        enabled: yes  
...
