---
- name: Deploy Web App
  hosts: n2
  become: yes

  tasks:
    - name: Install GIT
      yum:
        name: git
        state: present   

    - name: Host code
      git:
        repo: https://github.com/CeeyIT-Solutions/ecomm-3.git
        dest: /var/www/html  
    
...
