---
- name: Ensure /opt/devops directory exists on all managed nodes
  hosts: g1
  become: yes
  tasks:
    - name: Create /opt/devops directory
      file:
        path: /opt/devops
        state: directory
        mode: '0755'
...
